# Generated by Django 4.2.7 on 2025-11-14 16:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Xona nomi')),
                ('description', models.TextField(verbose_name='Tavsif')),
                ('order', models.IntegerField(unique=True, verbose_name='Tartib raqami')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faol')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Xona',
                'verbose_name_plural': 'Xonalar',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='UserStatistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_score', models.IntegerField(default=0, verbose_name='Jami ball')),
                ('rooms_completed', models.IntegerField(default=0, verbose_name='Tugallangan xonalar')),
                ('puzzles_completed', models.IntegerField(default=0, verbose_name='Tugallangan jumboqlar')),
                ('total_time', models.IntegerField(default=0, verbose_name='Jami vaqt (soniya)')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('current_room', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='current_users', to='game.room', verbose_name='Joriy xona')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='statistics', to=settings.AUTH_USER_MODEL, verbose_name='Foydalanuvchi')),
            ],
            options={
                'verbose_name': 'Foydalanuvchi statistikasi',
                'verbose_name_plural': 'Foydalanuvchi statistikasi',
            },
        ),
        migrations.CreateModel(
            name='Puzzle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Jumboq nomi')),
                ('description', models.TextField(verbose_name='Tavsif')),
                ('puzzle_type', models.CharField(choices=[('math', 'Matematika'), ('logic', 'Mantiqiy'), ('word', "So'z"), ('memory', 'Xotira'), ('pattern', 'Naqsh')], max_length=20, verbose_name='Jumboq turi')),
                ('question', models.TextField(verbose_name='Savol')),
                ('correct_answer', models.CharField(max_length=500, verbose_name="To'g'ri javob")),
                ('points', models.IntegerField(default=10, verbose_name='Ball')),
                ('order', models.IntegerField(verbose_name='Tartib raqami')),
                ('hint', models.TextField(blank=True, null=True, verbose_name='Maslahat')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='puzzles', to='game.room', verbose_name='Xona')),
            ],
            options={
                'verbose_name': 'Jumboq',
                'verbose_name_plural': 'Jumboqlar',
                'ordering': ['room', 'order'],
                'unique_together': {('room', 'order')},
            },
        ),
        migrations.CreateModel(
            name='UserProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_completed', models.BooleanField(default=False, verbose_name='Tugallangan')),
                ('started_at', models.DateTimeField(auto_now_add=True, verbose_name='Boshlangan vaqt')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Tugallangan vaqt')),
                ('time_taken', models.IntegerField(default=0, verbose_name="O'tkazilgan vaqt (soniya)")),
                ('attempts', models.IntegerField(default=0, verbose_name='Urinishlar soni')),
                ('score', models.IntegerField(default=0, verbose_name='Ball')),
                ('puzzle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_progress', to='game.puzzle', verbose_name='Jumboq')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_progress', to='game.room', verbose_name='Xona')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress', to=settings.AUTH_USER_MODEL, verbose_name='Foydalanuvchi')),
            ],
            options={
                'verbose_name': 'Foydalanuvchi progressi',
                'verbose_name_plural': 'Foydalanuvchi progresslari',
                'ordering': ['-completed_at', '-started_at'],
                'unique_together': {('user', 'puzzle')},
            },
        ),
    ]
